//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: messages_internal_command_out.proto
namespace ControleRobo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReceiveWheel")]
  public partial class ReceiveWheel : global::ProtoBuf.IExtensible
  {
    public ReceiveWheel() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private double _speed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReceiveRobot")]
  public partial class ReceiveRobot : global::ProtoBuf.IExtensible
  {
    public ReceiveRobot() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<ReceiveWheel> _wheels = new global::System.Collections.Generic.List<ReceiveWheel>();
    [global::ProtoBuf.ProtoMember(2, Name=@"wheels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ReceiveWheel> wheels
    {
      get { return _wheels; }
    }
  
    private double _battery_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"battery_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double battery_level
    {
      get { return _battery_level; }
      set { _battery_level = value; }
    }
    private int _has_ball;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"has_ball", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int has_ball
    {
      get { return _has_ball; }
      set { _has_ball = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ToIntelligence")]
  public partial class ToIntelligence : global::ProtoBuf.IExtensible
  {
    public ToIntelligence() {}
    
    private readonly global::System.Collections.Generic.List<ReceiveRobot> _robots = new global::System.Collections.Generic.List<ReceiveRobot>();
    [global::ProtoBuf.ProtoMember(1, Name=@"robots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ReceiveRobot> robots
    {
      get { return _robots; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
