//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: messages_internal_command.proto
namespace ControleRobo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommandWheel")]
  public partial class CommandWheel : global::ProtoBuf.IExtensible
  {
    public CommandWheel() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private double _speed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommandKicker")]
  public partial class CommandKicker : global::ProtoBuf.IExtensible
  {
    public CommandKicker() {}
    
    private double _speed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private bool _forced = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"forced", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool forced
    {
      get { return _forced; }
      set { _forced = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommandDribbler")]
  public partial class CommandDribbler : global::ProtoBuf.IExtensible
  {
    public CommandDribbler() {}
    
    private double _speed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private bool _forced = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"forced", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool forced
    {
      get { return _forced; }
      set { _forced = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommandRobot")]
  public partial class CommandRobot : global::ProtoBuf.IExtensible
  {
    public CommandRobot() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<CommandWheel> _wheels = new global::System.Collections.Generic.List<CommandWheel>();
    [global::ProtoBuf.ProtoMember(2, Name=@"wheels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CommandWheel> wheels
    {
      get { return _wheels; }
    }
  

    private CommandKicker _kicker = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"kicker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CommandKicker kicker
    {
      get { return _kicker; }
      set { _kicker = value; }
    }

    private CommandDribbler _dribbler = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dribbler", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CommandDribbler dribbler
    {
      get { return _dribbler; }
      set { _dribbler = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ToTransmission")]
  public partial class ToTransmission : global::ProtoBuf.IExtensible
  {
    public ToTransmission() {}
    
    private readonly global::System.Collections.Generic.List<CommandRobot> _robots = new global::System.Collections.Generic.List<CommandRobot>();
    [global::ProtoBuf.ProtoMember(1, Name=@"robots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CommandRobot> robots
    {
      get { return _robots; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
